#!/bin/sh
# https://github.com/mantisbt-plugins/source-integration

# generate by `openssl rand -hex 12` or similar.
API_KEY=6dcde9b4c68c4507f68b6ec3

# Repository ID. Get it after repository creating in MantisBT.
# if ID=all, all the repositories in MantisBT will be updated. You can automate it by configure a cron job or similar.
ID=11

CURL=/usr/bin/curl

URL="http://localhost/mantis/plugin.php?page=Source/import&api_key=${API_KEY}&id=${ID}"

${CURL} ${URL}
